Simple-Driver:
  normalize: true
  n_envs: 1
  n_timesteps: !!float 1e7
  policy: "MlpPolicy"
  batch_size: 256
  n_steps: 2000
  gamma: 0.9999
  learning_rate: !!float 7.77e-05
  ent_coef: 0.00429
  clip_range: 0.1
  n_epochs: 20
  gae_lambda: 0.95
  max_grad_norm: 5
  vf_coef: 0.19
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3.29, net_arch=[32, 32])"
